# GitHub Action for generating a contribution graph with a snake eating your contributions.

 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: amreen/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: amreen
            # Text on contribution graph 
            text: amreen
       - uses: amreenwafa/simple-push-action@v1
